# For parameter descriptions, please refer to the template parameter files for each node.

# GPS and IMU Localization
# 
# Params from https://github.com/clearpathrobotics/robot_localization/blob/kinetic-devel/params/ekf_template.yaml
# https://answers.ros.org/question/269631/robot_localization-gps-and-imu-minimal-example-not-working/
# Tutorial from The Construct https://www.youtube.com/watch?v=nQZeAafDEJE
# https://github.com/ros-agriculture/tractor_localization/blob/master/params/gps_imu_localization.yaml
# 




frequency: 30
delay: 3.0
# ~~~~~~ IF USE IMU  for heading angle~~~~~~~
# Magnetic declination in radians obtained for Gwangju according to
# https://answers.ros.org/question/380637/right-value-of-magnetic_declination_radians/
# https://www.magnetic-declination.com/Korea%20(South)/Gwangju/1412533.html          
#magnetic_declination_radians: 0.1418953
# NWU coordinates to ENU coordinates
#yaw_offset: -1.5705963 

# ~~~~~~ IF USE GPS TDR-3000 for heading angle~~~~~~~
magnetic_declination_radians: 0.0
# GPS points true north, but NMEA driver correct to ENU frame
yaw_offset: 3.1411926 # But antennas are inverted so they must be compesated 180 degrees


zero_altitude: true

broadcast_cartesian_transform: true
broadcast_cartesian_transform_as_parent_frame: false
publish_filtered_gps: true


use_odometry_yaw: false
wait_for_datum: false

