  gazebo_ros_control:
    pid_gains:
      steering_fl_joint:
        p: 50
        i: 1
        d: 0.01
      steering_fr_joint:
        p: 50
        i: 1
        d: 0.01
      steering_bl_joint:
        p: 50
        i: 1
        d: 0.01
      steering_br_joint:
        p: 50
        i: 1
        d: 0.01
      wheel_fl_joint: #front_left_wheel
        p: 1000.0
        i: 1
        d: 0.0
      wheel_fr_joint: #front_right_wheel
        p: 1000.0
        i: 1
        d: 0.0
      wheel_bl_joint: #rear_left_wheel
        p: 1000.0
        i: 1
        d: 0.0
      wheel_br_joint: #rear_right_wheel
        p: 1000.0
        i: 1
        d: 0.0
