"""
Robot parameters
"""
robot = {
  "WHEELS_RADIUS": 0.41,
  "DRIVING_GEAR_BOX_RATIO": 30,
  "MAX_LINEAR_SPEED": 2.8,
  "MAX_STEERING_SPEED": 1,
  "STEERING_GEAR_BOX_RATIO": 50,
  "MIN_STEERING_ANGLE": 45,
  "MAX_STEERING_ANGLE": 135,
  "AXLE_TRACK_DISTANCE":1,
  "WHEEL_BASE_DISTANCE":1
}