"""
Robot parameters
"""
robot = {
  "WHEELS_RADIUS": 0.350,
  "DRIVING_GEAR_BOX_RATIO": 1,
  "MAX_LINEAR_SPEED": 2.8,
  "MAX_STEERING_SPEED": 1,
  "STEERING_GEAR_BOX_RATIO": 30,
  "MIN_STEERING_ANGLE": 45,
  "MAX_STEERING_ANGLE": 135
}